# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ForwardingRule(Model):
    """ForwardingRule.

    :param field: Possible values include: 'from', 'to', 'subject'
    :type field: str or ~mailosaur.models.enum
    :param operator: Possible values include: 'endsWith', 'startsWith',
     'contains'
    :type operator: str or ~mailosaur.models.enum
    :param value:
    :type value: str
    :param forward_to:
    :type forward_to: str
    """

    _attribute_map = {
        'field': {'key': 'field', 'type': 'str'},
        'operator': {'key': 'operator', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
        'forward_to': {'key': 'forwardTo', 'type': 'str'},
    }

    def __init__(self, field=None, operator=None, value=None, forward_to=None):
        super(ForwardingRule, self).__init__()
        self.field = field
        self.operator = operator
        self.value = value
        self.forward_to = forward_to
