# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Image(Model):
    """Image.

    :param src:
    :type src: str
    :param alt:
    :type alt: str
    """

    _attribute_map = {
        'src': {'key': 'src', 'type': 'str'},
        'alt': {'key': 'alt', 'type': 'str'},
    }

    def __init__(self, src=None, alt=None):
        super(Image, self).__init__()
        self.src = src
        self.alt = alt
