# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Link(Model):
    """Link.

    :param href:
    :type href: str
    :param text:
    :type text: str
    """

    _attribute_map = {
        'href': {'key': 'href', 'type': 'str'},
        'text': {'key': 'text', 'type': 'str'},
    }

    def __init__(self, href=None, text=None):
        super(Link, self).__init__()
        self.href = href
        self.text = text
