# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class MailosaurError(Model):
    """MailosaurError.

    :param type: Possible values include: 'None', 'ValidationError',
     'AuthenticationError', 'PermissionDeniedError', 'ResourceNotFoundError'
    :type type: str or ~mailosaur.models.enum
    :param messages:
    :type messages: dict[str, str]
    :param model:
    :type model: object
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'messages': {'key': 'messages', 'type': '{str}'},
        'model': {'key': 'model', 'type': 'object'},
    }

    def __init__(self, type=None, messages=None, model=None):
        super(MailosaurError, self).__init__()
        self.type = type
        self.messages = messages
        self.model = model


class MailosaurException(HttpOperationError):
    """Server responsed with exception of type: 'MailosaurError'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(MailosaurException, self).__init__(deserialize, response, 'MailosaurError', *args)
