# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageSummary(Model):
    """MessageSummary.

    :param id:
    :type id: str
    :param server:
    :type server: str
    :param rcpt:
    :type rcpt: list[~mailosaur.models.MessageAddress]
    :param sender:
    :type sender: list[~mailosaur.models.MessageAddress]
    :param to:
    :type to: list[~mailosaur.models.MessageAddress]
    :param cc:
    :type cc: list[~mailosaur.models.MessageAddress]
    :param bcc:
    :type bcc: list[~mailosaur.models.MessageAddress]
    :param received:
    :type received: datetime
    :param subject:
    :type subject: str
    :param summary:
    :type summary: str
    :param attachments:
    :type attachments: int
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'server': {'key': 'server', 'type': 'str'},
        'rcpt': {'key': 'rcpt', 'type': '[MessageAddress]'},
        'sender': {'key': 'from', 'type': '[MessageAddress]'},
        'to': {'key': 'to', 'type': '[MessageAddress]'},
        'cc': {'key': 'cc', 'type': '[MessageAddress]'},
        'bcc': {'key': 'bcc', 'type': '[MessageAddress]'},
        'received': {'key': 'received', 'type': 'iso-8601'},
        'subject': {'key': 'subject', 'type': 'str'},
        'summary': {'key': 'summary', 'type': 'str'},
        'attachments': {'key': 'attachments', 'type': 'int'},
    }

    def __init__(self, id, server=None, rcpt=None, sender=None, to=None, cc=None, bcc=None, received=None, subject=None, summary=None, attachments=None):
        super(MessageSummary, self).__init__()
        self.id = id
        self.server = server
        self.rcpt = rcpt
        self.sender = sender
        self.to = to
        self.cc = cc
        self.bcc = bcc
        self.received = received
        self.subject = subject
        self.summary = summary
        self.attachments = attachments
