# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageContent(Model):
    """MessageContent.

    :param links:
    :type links: list[~mailosaur.models.Link]
    :param images:
    :type images: list[~mailosaur.models.Image]
    :param body:
    :type body: str
    """

    _attribute_map = {
        'links': {'key': 'links', 'type': '[Link]'},
        'images': {'key': 'images', 'type': '[Image]'},
        'body': {'key': 'body', 'type': 'str'},
    }

    def __init__(self, links=None, images=None, body=None):
        super(MessageContent, self).__init__()
        self.links = links
        self.images = images
        self.body = body
