# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageHeader(Model):
    """MessageHeader.

    :param field: Header key.
    :type field: str
    :param value: Header value.
    :type value: str
    """

    _attribute_map = {
        'field': {'key': 'field', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, field=None, value=None):
        super(MessageHeader, self).__init__()
        self.field = field
        self.value = value
