# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageAddress(Model):
    """MessageAddress.

    :param name: Display name, if one is specified.
    :type name: str
    :param email: Email address (applicable to email messages).
    :type email: str
    :param phone: Phone number (applicable to SMS messages).
    :type phone: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'email': {'key': 'email', 'type': 'str'},
        'phone': {'key': 'phone', 'type': 'str'},
    }

    def __init__(self, name=None, email=None, phone=None):
        super(MessageAddress, self).__init__()
        self.name = name
        self.email = email
        self.phone = phone
