# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Metadata(Model):
    """Advanced use case content related to the message.

    :param headers: Email headers.
    :type headers: list[~mailosaur.models.MessageHeader]
    """

    _attribute_map = {
        'headers': {'key': 'headers', 'type': '[MessageHeader]'},
    }

    def __init__(self, headers=None):
        super(Metadata, self).__init__()
        self.headers = headers
