# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SearchCriteria(Model):
    """SearchCriteria.

    :param sent_to: The full email address to which the target email was sent.
    :type sent_to: str
    :param subject: The value to seek within the target email's subject line.
    :type subject: str
    :param body: The value to seek within the target email's HTML or text
     body.
    :type body: str
    """

    _attribute_map = {
        'sent_to': {'key': 'sentTo', 'type': 'str'},
        'subject': {'key': 'subject', 'type': 'str'},
        'body': {'key': 'body', 'type': 'str'},
    }

    def __init__(self, sent_to=None, subject=None, body=None):
        super(SearchCriteria, self).__init__()
        self.sent_to = sent_to
        self.subject = subject
        self.body = body
