# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Server(Model):
    """Server.

    :param id: Unique identifier for the server. Used as username for
     SMTP/POP3 authentication.
    :type id: str
    :param password: SMTP/POP3 password.
    :type password: str
    :param name: A name used to identify the server.
    :type name: str
    :param users: Users (excluding administrators) who have access to the
     server.
    :type users: list[str]
    :param messages: The number of messages currently in the server.
    :type messages: int
    :param forwarding_rules: The rules used to manage email forwarding for
     this server.
    :type forwarding_rules: list[~mailosaur.models.ForwardingRule]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'password': {'key': 'password', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'users': {'key': 'users', 'type': '[str]'},
        'messages': {'key': 'messages', 'type': 'int'},
        'forwarding_rules': {'key': 'forwardingRules', 'type': '[ForwardingRule]'},
    }

    def __init__(self, id=None, password=None, name=None, users=None, messages=None, forwarding_rules=None):
        super(Server, self).__init__()
        self.id = id
        self.password = password
        self.name = name
        self.users = users
        self.messages = messages
        self.forwarding_rules = forwarding_rules
