# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SpamAssassinRule(Model):
    """SpamAssassinRule.

    :param score:
    :type score: float
    :param rule:
    :type rule: str
    :param description:
    :type description: str
    """

    _attribute_map = {
        'score': {'key': 'score', 'type': 'float'},
        'rule': {'key': 'rule', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
    }

    def __init__(self, score=None, rule=None, description=None):
        super(SpamAssassinRule, self).__init__()
        self.score = score
        self.rule = rule
        self.description = description
